git:
  depth: 1
  quiet: true
  submodules: false
language: cpp
dist: bionic
compiler: clang
os: linux
before_install:
  echo "before_install"
install:
  echo "install"
script:
  bash -c "./ci/configure.sh && ./ci/build.sh && ./ci/test.sh"
after_success:
  
#branches:
#notifications:
#env:
#  global:
    
