git:
  depth: 1
  quiet: true
  submodules: false
language: cpp
dist: bionic
compiler: clang
os: linux
#addons:
#  apt:
#    packages:
#      - cmake
#      - ninja-build
#before_install:
#install:
#before_script:
script:
  cmake -G Ninja --configure . && cmake --build . && ctest .
after_success:
  
#branches:
#notifications:
#env:
#  global:
    
